name: CI_CD_pipline_to_AWS_Elastic_Beanstalk

env:
  EB_PACKAGE_S3_BUCKET_NAME : "sergey-django-githubactions" #S3 bucket name where to stopre zip file
  EB_APPLICATION_NAME       : "Flask"
  EB_ENVIRONMENT_NAME       : "Flask-env"
  DEPLOY_PACKAGE_NAME       : "app_${{github.sha}}" #github.sha - hash of commit
  AWS_REGION                : "us-east-1"

on:
# Triggers the workflow on push events but only for the main branch
  push:
    branches :
      - main



jobs:
  ci_job:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone the repo
        uses: actions/checkout@v2
      
      - name: Create ZIP package for deplyment
        run : zip -r ${{env.DEPLOY_PACKAGE_NAME}}.zip . -x *.git*
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id     :  ${{secrets.GA_AWS_ACCESS_KEY}}
          aws-secret-access-key :  ${{secrets.GA_AWS_SECRET_KEY}}
          aws-region            :  ${{env.AWS_REGION}}
      
      - name: Copy deployment package to S3 bucket
        run : aws s3 cp ${{env.DEPLOY_PACKAGE_NAME}}.zip s3://${{env.EB_PACKAGE_S3_BUCKET_NAME}}/
  
  
  cd_job:
    runs-on: ubuntu-latest
    needs: [ci_job]
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id     :  ${{secrets.GA_AWS_ACCESS_KEY}}
          aws-secret-access-key :  ${{secrets.GA_AWS_SECRET_KEY}}
          aws-region            :  ${{env.AWS_REGION}       
      
      - name: Create new ElasticBeanstalk application
      
      - name: Create Elastic Beanstalk Application
        run : | 
          aws-elasticbeanstalk create-application-version \
          --application-name ${{env.EB_APPLICATION_NAME}} \
          --source-bundle S3Bucket="${{env.EB_PACKAGE_S3_BUCKET_NAME}}", S3Key="${{env.DEPLOY_PACKAGE_NAME}}.zip" \
          --version-label "Ver-${{github.sha}}" \
          --description "CommitSHA - ${{github.sha}}"
           
      - name: Deply new Elastic Beanstalk Application Version
        run : aws elasticbeanstalk update-environment \
              --environment-name ${{EB_ENVIRONMENT_NAME}} \
              --version-label "Ver-${{github.sha}}" 
         
